POST http://localhost:9999/api/tokens
Content-Type: application/json

{
  "username": "parviz",
  "password": "par"
}

> {% client.global.set("auth_token", response.body.token); %}

###

POST http://localhost:9999/api/tokens
Content-Type: application/json

{
  "username": "admin",
  "password": "pass1"
}

###

GET http://localhost:9999/api/users/me
Authorization: Bearer {{auth_token}}

###

DELETE http://localhost:9999/api/users/1
Authorization: Bearer {{auth_token}}

###

POST http://localhost:9999/api/newUser
Content-Type: application/json

{
  "name" : "name",
  "login": "parviz",
  "password": "par"
}

###

GET http://localhost:9999/api/rooms/list

###
